module.exports =   EnumMaterial =  ["SUJO", "SUJO/PRONTA", "SUJO/INCOMPLETA", "LIMPEZA INICIADA", 
"LIMPO","LIMPO/EST. TERCEIRO", "LIMPO/DESINFECTADO", "PREPARO INICIADO", "PREPARO INICIADO/DESINFECTADO",
"EMBALADO", "EMBALADO/LIBERADO", "ESTERILIZAÇÃO INICIADA", "ESTERILIZADO", "ESTERILIZADO/TERCEIRO",
"LIBERADO LIMPEZA", "LIBERADO PREPARO", "LIBERADO CC", "LIBERADO RECEBIMENTO", "EM MANUTENÇÃO", 
"RETIRADO TERCEIRO", "RECEBIMENTO PENDENTE", "ENTRADA C/C PENDENTE", "SAIDA C/C PENDENTE",
"LIBERADO PARA SETOR", "ROUPARIA", "ACESSORIO", "MATERIAL BANHO", "FINALIZADA"]