stages:
  - start
  - test

iniciar_api:
  stage: start
  image: node:17-alpine3.14
  before_script:
    - npm install
  script:
    - npm start
  after_script:

realizar_testes:
  stage: test
  needs:
    - job: iniciar_api
  script:
    - npm test
  artifacts:
    when: always
    reports:
      junit: junit.xml
