stages:
  - test
  - start

iniciar_api:
  stage: start
  image: node:17-alpine3.14
before_script:
    - npm install
      script:
    - npm start

realizar_testes:
  stage: test
    needs:
    - criar_imagens
  script:
    - npm test
  artifacts:
    when: always
    reports:
      junit: junit.xml
